apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: kubia
  name: kubia
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: main
        image: luksa/kubia-java-arm:leader-election
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
      - name: elector
        imagePullPolicy: Always
        image: luksa/metaparticle-elector-arm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubia
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
