apiVersion: v1
kind: Pod
metadata:
  name: kubia
  labels:
    app: kubia
spec:
  containers:
  - name: main
    image: luksa/kubia-java-arm:broken
    ports:
    - name: http
      containerPort: 8080
