apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
  labels:
    app: kubia
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
        led-color: cyan
    spec:
      containers:
      - name: main
        image: luksa/kubia-java-arm:v4
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            port: 8080
            path: /healthz/readiness
        ports:
        - name: http
          containerPort: 8080
