apiVersion: v1
kind: Pod
metadata:
  name: system-info-limited-use-cgroups
spec:
  restartPolicy: OnFailure
  containers:
  - name: main
    image: luksa/java-system-info
    env:
    - name: JAVA_OPTIONS
      value: "-XX:+UseCGroupMemoryLimitForHeap"
    resources:
      limits:
        cpu: 1
        memory: 20M
